services:
  - type: web
    name: expense-tracker
    env: node
    buildCommand: |
      npm install
      rm -rf dist
      npm run build:all
      ls -la dist
      echo "Build completed. Contents of dist directory:"
      find dist -type f
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
